### ISSUE TITLE
any progress?

### ISSUE THREAD

**Issue by parrt** [janyou/Antlr-Swift-Runtime#1]
hi. are you any closer to finishing this? Need help?

**Comment by janyou** [comment]
Hi Professor:
  I have already finished it (Runtime Testsuite has been passed@xCode 7.2.1).
  Would you please make a branch？
  please refer to [Run Runtime Testsuite](https://github.com/janyou/ANTLR-Swift-Target/blob/master/RuntimeTestsuite.md)
  (note: other targets'.test.stg should be added one line : `OptionalValue(value) ::= "<value>"`)

**Comment by artyom-razinov** [comment]
Hi, I used your project. It actually works for large grammars like Swift.g4 (with little modifications to generated files, e.g. on Swift grammar it fails on semantic predicates). However, there are issues. E.g.: you have this function:

`public static func readFile(fileName: String, _ encoding: NSStringEncoding = NSUTF8StringEncoding) -> [Character]`

It actually does not read file as expected. It tries to search it in bundle. So if someone like me would integrate your project in a framework, this function will not work, because creators of framework expect this function to open file at path. Why not to implement this desired behavior? Users can pass file path of bundled file as before.

I also added Carthage support to your framework and I can make pull request to your repo.

By the way, you added "final" to some functions in your latest commit. I suggest you to make whole classes final instead. It is a good practice, it follows SOLID and clean architecture. You should prefer composition over inheritance. More about it: https://en.wikipedia.org/wiki/Composition_over_inheritance

If class is marked final, all functions and variables in it became final. It gives noticable increase in performance, but only when final function is invoked many and many times. ANTLR runtime is such case, ordinary iOS applications are not, but I develop iOS applications and use final, because it prevents programmers to use bad architectural solutions.

**Comment by artyom-razinov** [comment]
Some other notes about actual usage experience. Your code generation tool makes JSON file. It would be better if that file be code, so they can be simply compiled in framework. Also it would give little more speed. In my project I replaced generated json files with swift classes (manually).

**Comment by artyom-razinov** [comment]
About migration to Xcode 7.3. Xcode 7.3 has a critical bug in compiler (https://bugs.swift.org/browse/SR-815). Apps built with Xcode 7.3 for iOS 7 would crash. As you are writing a framework, and you have iOS target, I suggest you not to update to Xcode 7.3 if you want your framework to be used in iOS 7 projects. However, now is a time to drop iOS 7 support on projects. I think many large projects will drop iOS 7 in current year.

**Comment by janyou** [comment]
@artyom-razinov, Thanks for your advice.

i use profiler to test performance. "final" method runs faster than "final" class, It‘s strange.

**Comment by janyou** [comment]
"JSON in class" 
 Antlr-Swift-Runtime: 1053e47  ANTLR-Swift-Target: [3b72562](https://github.com/janyou/ANTLR-Swift-Target/commit/3b72562a3a44d288e7cd6df8a28718e0cebbd53c)

**Comment by parrt** [comment]
Hi. I'll add this to my todo list to test and then try to integrate into main repo :)  thanks! Keep on tweaking/fixing/hacking and I'll incorporate soon.

**Comment by janyou** [comment]
Great!
